#if DEBUG
using Multiplayer.Debugging.Protocol;
using System;
using System.Linq;

namespace Multiplayer.Debugging.RuntimeTests;

internal static class RuntimeTestCatalog
{
    private static readonly RuntimeTestDescriptorDto[] descriptors =
    {
        new() { TestId = "runtime.self-check", DisplayName = "Runtime self-check", Category = "Harness", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "runtime-self-check" }, TimeoutMilliseconds = 5000 },
        new() { TestId = "runtime.control-status", DisplayName = "Input ownership and world-state status", Category = "Harness", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "runtime-input-control" }, TimeoutMilliseconds = 5000 },
        new() { TestId = "runtime.interaction-mode", DisplayName = "Set pickup or screenspace interaction mode", Category = "Harness", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "runtime-input-control" }, TimeoutMilliseconds = 5000 },
        new() { TestId = "runtime.neutralize", DisplayName = "Restore neutral gameplay state", Category = "Harness", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "neutral-world-state" }, TimeoutMilliseconds = 10000 },
        new() { TestId = "runtime.csharp-execute", DisplayName = "Execute externally compiled C#", Category = "Harness", Fidelity = "UnrestrictedDebugCode+MainThread", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "runtime-csharp-execution" }, TimeoutMilliseconds = 120000 },
        new() { TestId = "environment.status", DisplayName = "Environment readiness", Category = "Environment", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "environment-orchestration" }, TimeoutMilliseconds = 5000 },
        new() { TestId = "environment.save-catalog", DisplayName = "Available host saves", Category = "Environment", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "environment-orchestration" }, TimeoutMilliseconds = 5000 },
        new() { TestId = "environment.host-save", DisplayName = "Host configured save", Category = "Environment", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "environment-orchestration" }, TimeoutMilliseconds = 15000 },
        new() { TestId = "environment.host-latest-save", DisplayName = "Host latest save (legacy)", Category = "Environment", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "environment-orchestration" }, TimeoutMilliseconds = 15000 },
        new() { TestId = "environment.connect-client", DisplayName = "Connect runtime client", Category = "Environment", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "environment-orchestration" }, TimeoutMilliseconds = 15000 },
        new() { TestId = "player.teleport", DisplayName = "Native player teleport", Category = "Arrangement", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "player-teleport" }, TimeoutMilliseconds = 15000 },
        new() { TestId = "player.position", DisplayName = "Read or copy player world position", Category = "Arrangement", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "player-teleport" }, TimeoutMilliseconds = 5000 },
        new() { TestId = "item.look-at", DisplayName = "Aim camera at a networked item", Category = "Items", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "camera-item-targeting" }, TimeoutMilliseconds = 10000 },
        new() { TestId = "item.pickup", DisplayName = "Raycast world pickup", Category = "Items", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "non-vr-item-interaction" }, TimeoutMilliseconds = 10000 },
        new() { TestId = "item.drop", DisplayName = "Held-item drop", Category = "Items", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "non-vr-item-interaction" }, TimeoutMilliseconds = 10000 },
        new() { TestId = "item.throw", DisplayName = "Held-item throw", Category = "Items", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "non-vr-item-interaction" }, TimeoutMilliseconds = 10000 },
        new() { TestId = "inventory.inspect", DisplayName = "Inspect local inventory", Category = "Inventory", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "inventory-runtime-arrangement" }, TimeoutMilliseconds = 5000 },
        new() { TestId = "inventory.prefab-catalog", DisplayName = "List item prefabs", Category = "Inventory", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "inventory-runtime-arrangement" }, TimeoutMilliseconds = 5000 },
        new() { TestId = "inventory.fixture-create", DisplayName = "Create authoritative inventory fixture", Category = "Inventory", Fidelity = "DirectState+ServerAuthority", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-inventory-fixtures" }, TimeoutMilliseconds = 15000 },
        new() { TestId = "inventory.fixture-place", DisplayName = "Place authoritative inventory fixture", Category = "Inventory", Fidelity = "DirectState+ServerAuthority", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-inventory-fixtures" }, TimeoutMilliseconds = 10000 },
        new() { TestId = "inventory.fixture-destroy", DisplayName = "Retire authoritative inventory fixture", Category = "Inventory", Fidelity = "DirectState+ServerAuthority", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-inventory-fixtures" }, TimeoutMilliseconds = 10000 },
        new() { TestId = "inventory.fixture-clean-local", DisplayName = "Purge local runtime fixture representations", Category = "Inventory", Fidelity = "DirectState+FixtureIdentity", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "inventory-runtime" }, TimeoutMilliseconds = 10000 },
        new() { TestId = "inventory.local-place", DisplayName = "Arrange item through local DV inventory", Category = "Inventory", Fidelity = "GameplayMethod", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "inventory-runtime-arrangement" }, TimeoutMilliseconds = 10000 }
        ,new() { TestId = "train.track-catalog", DisplayName = "Railway track catalogue", Category = "Train Fixtures", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "train-track-catalog" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.track-nearest", DisplayName = "Capture nearest track fixture anchor", Category = "Train Fixtures", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "train-track-catalog" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-location-catalog", DisplayName = "Named train fixture locations", Category = "Train Fixtures", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "train-track-catalog" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-teleport-location", DisplayName = "Teleport to named train fixture location", Category = "Train Fixtures", Fidelity = "GameplayMethod+LocalPlayer", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "train-track-catalog" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-create", DisplayName = "Create authoritative train fixture", Category = "Train Fixtures", Fidelity = "DirectState+ServerAuthority", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-train-fixtures" }, TimeoutMilliseconds = 60000 }
        ,new() { TestId = "train.fixture-catalog", DisplayName = "Train livery fixture catalogue", Category = "Train Fixtures", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "train-fixture-observation" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-observe", DisplayName = "Observe projected train fixture", Category = "Train Fixtures", Fidelity = "ReadOnly+ProjectionBarrier", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "train-fixture-observation" }, TimeoutMilliseconds = 20000 }
        ,new() { TestId = "train.fixture-status", DisplayName = "Train fixture ledger status", Category = "Train Fixtures", Fidelity = "ReadOnly", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "train-fixture-observation" }, TimeoutMilliseconds = 5000 }
        ,new() { TestId = "train.fixture-acquire-route", DisplayName = "Acquire fixture junction route lease", Category = "Train Fixtures", Fidelity = "DirectState+ServerAuthority", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-train-fixtures" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-start", DisplayName = "Start fixture automatic speed control", Category = "Train Fixtures", Fidelity = "GameplayControls+ServerAuthority", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-train-fixtures" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-stop", DisplayName = "Stop fixture automatic speed control", Category = "Train Fixtures", Fidelity = "GameplayControls+ServerAuthority", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-train-fixtures" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-wait-motion", DisplayName = "Wait for fixture locomotive motion", Category = "Train Fixtures", Fidelity = "ReadOnly+MotionBarrier", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "host-train-fixtures" }, TimeoutMilliseconds = 30000 }
        ,new() { TestId = "train.fixture-set-control", DisplayName = "Set one fixture locomotive control", Category = "Train Fixtures", Fidelity = "GameplayControls+ServerAuthority", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-train-fixtures" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-relocate", DisplayName = "Atomically relocate a stopped fixture consist", Category = "Train Fixtures", Fidelity = "DirectState+ServerAuthority+AtomicProjection", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-train-fixtures" }, TimeoutMilliseconds = 30000 }
        ,new() { TestId = "train.fixture-place-player", DisplayName = "Place local player aboard a fixture car", Category = "Train Fixtures", Fidelity = "GameplayMethod+LocalPlayer", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "train-fixture-observation" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-evacuate-player", DisplayName = "Evacuate local player from a fixture car", Category = "Train Fixtures", Fidelity = "GameplayMethod+LocalPlayer", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "train-fixture-observation" }, TimeoutMilliseconds = 15000 }
        ,new() { TestId = "train.fixture-cleanup", DisplayName = "Delete and verify train fixture", Category = "Train Fixtures", Fidelity = "DirectState+ServerAuthority", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-train-fixtures" }, TimeoutMilliseconds = 30000 }
        ,new() { TestId = "train.fixture-cleanup-orphans", DisplayName = "Delete orphaned train fixtures", Category = "Train Fixtures", Fidelity = "DirectState+FixtureIdentity", MutationKind = RuntimeTestMutationKind.IsolatedMutation, RequiredCapabilities = new[] { "host-train-fixtures" }, TimeoutMilliseconds = 30000 }
        ,new() { TestId = "train.item-observe-motion", DisplayName = "Observe item in a moving fixture car", Category = "Train Item Physics", Fidelity = "ReadOnly+TrainRelativeSpatialBarrier", MutationKind = RuntimeTestMutationKind.ReadOnly, RequiredCapabilities = new[] { "train-item-spatial-observation" }, TimeoutMilliseconds = 30000 }
    };

    private static RuntimeTestDescriptorDto[] AllDescriptors => descriptors
        .Concat(RuntimeTestScenarioRegistry.Descriptors).ToArray();

    public static string[] Commands => AllDescriptors.Select(item => item.TestId).ToArray();
    public static RuntimeTestDescriptorDto[] Descriptors => AllDescriptors
        .Select(RuntimeTestDescriptorCloner.Clone).ToArray();
    public static RuntimeTestDescriptorDto Find(string id) => AllDescriptors.FirstOrDefault(item =>
        string.Equals(item.TestId, id, StringComparison.Ordinal));
}
#endif
